import { Button, Checkbox, Input, Radio, Select, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Textarea } from "@johnshandux/ledger-design-system";
import { DocsLayout } from "../../_components/DocsLayout";
import { componentCatalog, componentRoadmap } from "@/content/design-system-docs";
import { DataTableExample } from "./DataTableExample";
import Link from "next/link";
import { AlertExample, AspectRatioExample, AvatarExample, BadgeExample, CardExample, ProgressExample, SeparatorExample, SkeletonExample, SpinnerExample } from "@johnshandux/ledger-design-system/examples";

const comingSoonNames = ["Tabs", "Breadcrumb", "Pagination", "EmptyState", "Switch", "SearchField"] as const;
const comingSoon = comingSoonNames.flatMap((name) => componentRoadmap.filter((component) => component.name === name));

export default function ComponentsPage() {
  return <DocsLayout eyebrow="Source-backed catalogue" title="Components" intro="The catalogue reflects the current package exports and contracts. Root-entry components remain safe for React Server Components; interaction primitives and icons use dedicated client-aware entries.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Live examples</p><h2>Actions and form controls</h2></div><p>These examples render the actual components from the workspace package rather than site-owned imitations.</p></div><div className="component-gallery"><article className="component-specimen"><div><h3>Button</h3><p>Use intent-based variants. Destructive is reserved for destructive or irreversible actions.</p></div><div className="demo-surface demo-actions"><Button>Continue</Button><Button variant="secondary">Save draft</Button><Button variant="destructive">Delete beneficiary</Button></div></article><article className="component-specimen"><div><h3>Input and Select</h3><p>Text-based controls require accessible labels, which remain visible unless a contextually clear search control deliberately hides one.</p></div><div className="demo-surface form-demo"><Input label="Business name" hint="Use the registered company name." placeholder="Example Manufacturing Ltd" /><Select label="Account currency" placeholder="Choose a currency" defaultValue="" options={[{ label: "Pound sterling", value: "GBP" }, { label: "Euro", value: "EUR" }, { label: "US dollar", value: "USD" }]} /></div></article><article className="component-specimen"><div><h3>Textarea, Checkbox and Radio</h3><p>Native semantics and browser behaviour remain intact beneath Ledger styling.</p></div><div className="demo-surface form-demo"><Textarea label="Payment note" placeholder="Add context for the approver" /><Checkbox label="Include remittance advice" hint="Sent after the payment is released." /><div role="group" aria-labelledby="payment-speed-label"><strong id="payment-speed-label" className="control-group-label">Payment speed</strong><Radio name="payment-speed" label="Standard" defaultChecked /><Radio name="payment-speed" label="Same day" /></div></div></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Button sizing</p><h2>Default and constrained actions</h2></div><p>The default remains appropriate for primary tasks. Small is available for constrained secondary actions and is not applied globally on mobile.</p></div><div className="demo-surface demo-actions"><Button>Default size</Button><Button size="small" variant="secondary">Small size</Button></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Data display</p><h2>Semantic Table composition</h2></div><p>Products own the records and financial meaning. Ledger supplies semantic table structure and alignment.</p></div><div className="demo-surface table-scroll"><Table ariaLabel="Example accounts"><TableHead><TableRow><TableHeaderCell>Account</TableHeaderCell><TableHeaderCell>Currency</TableHeaderCell><TableHeaderCell align="right">Available</TableHeaderCell></TableRow></TableHead><TableBody><TableRow><TableCell>Operating account</TableCell><TableCell>GBP</TableCell><TableCell align="right">£248,905.42</TableCell></TableRow><TableRow><TableCell>European operations</TableCell><TableCell>EUR</TableCell><TableCell align="right">€94,620.50</TableCell></TableRow></TableBody></Table></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Interactive data display</p><h2>DataTable</h2></div><p>DataTable composes Table with typed columns, configurable sorting, pagination, density, overflow and data-state foundations.</p></div><div className="demo-surface"><DataTableExample /></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Loading and layout</p><h2>Structural foundations</h2></div><p>These examples are shared with Storybook and exercise the public component APIs.</p></div><div className="component-gallery"><article className="component-specimen"><div><h3>Separator</h3><p>Creates a visual or semantic boundary.</p></div><div className="demo-surface"><SeparatorExample /></div></article><article className="component-specimen"><div><h3>Skeleton</h3><p>Reserves approximate layout while content loads.</p></div><div className="demo-surface"><SkeletonExample /></div></article><article className="component-specimen"><div><h3>Spinner</h3><p>Communicates indeterminate progress.</p></div><div className="demo-surface"><SpinnerExample /></div></article><article className="component-specimen"><div><h3>AspectRatio</h3><p>Reserves a responsive shape for media.</p></div><div className="demo-surface"><AspectRatioExample /></div></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Feedback and surfaces</p><h2>Status and content surfaces</h2></div><p>Semantic status and structured surfaces stay non-interactive and server-safe.</p></div><div className="component-gallery"><article className="component-specimen"><div><h3>Badge</h3><p>Communicates compact status with meaningful text.</p></div><div className="demo-surface"><BadgeExample /></div></article><article className="component-specimen"><div><h3>Alert</h3><p>Presents important static feedback without creating an automatic live region.</p></div><div className="demo-surface"><AlertExample /></div></article><article className="component-specimen"><div><h3>Card</h3><p>Groups related content with border and spacing rather than default elevation.</p></div><div className="demo-surface"><CardExample /></div></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Progress and identity</p><h2>Operation and identity states</h2></div><p>Accessible progress semantics and resilient image fallback sit behind dedicated client entries.</p></div><div className="component-gallery"><article className="component-specimen"><div><h3>Progress</h3><p>Communicates measurable or indeterminate operation progress.</p></div><div className="demo-surface"><ProgressExample /></div></article><article className="component-specimen"><div><h3>Avatar</h3><p>Represents a person or organisation with resilient fallback text.</p></div><div className="demo-surface"><AvatarExample /></div></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Component index</p><h2>Explore every component</h2></div><p>Open a component page for its purpose, public contract, examples and implementation guidance.</p></div><nav aria-label="Component index"><ul className="component-index">{componentCatalog.map((item) => <li key={item.name}><Link href={`/design-system/components/${item.slug}`}>{item.name}</Link></li>)}</ul></nav></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Coming soon</p><h2>Next on the roadmap</h2></div><p>A focused preview of capabilities being considered next. Details may evolve as their component specifications are reviewed.</p></div><ul className="coming-soon-list">{comingSoon.map((item) => <li key={item.name}><strong>{item.name}</strong><span>{item.purpose}</span></li>)}</ul></section>
    <section className="docs-section status-panel"><div><p className="eyebrow">Important distinction</p><h2>Link is a convention, not a React component.</h2></div><p>Applications use semantic anchors and apply <code>.ledger-link</code>. Ledger owns the visual treatment; the application owns routing, external-link detection, permissions and navigation state.</p></section>
  </DocsLayout>;
}
