import { Button, Checkbox, Input, Radio, Select, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Textarea } from "@johnshandux/ledger-design-system";
import { DocsLayout } from "../../_components/DocsLayout";
import { componentCatalog } from "@/content/design-system-docs";

const statuses = ["Implemented", "Dedicated entry", "Convention", "Planned"] as const;

export default function ComponentsPage() {
  return <DocsLayout eyebrow="Source-backed catalogue" title="Components" intro="The catalogue reflects the current package exports and contracts. Root-entry components remain safe for React Server Components; interaction primitives and icons use dedicated client-aware entries.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Live examples</p><h2>Actions and form controls</h2></div><p>These examples render the actual components from the workspace package rather than site-owned imitations.</p></div><div className="component-gallery"><article className="component-specimen"><div><h3>Button</h3><p>Use intent-based variants. Destructive is reserved for destructive or irreversible actions.</p></div><div className="demo-surface demo-actions"><Button>Continue</Button><Button variant="secondary">Save draft</Button><Button variant="destructive">Delete beneficiary</Button></div></article><article className="component-specimen"><div><h3>Input and Select</h3><p>Text-based controls require accessible labels, which remain visible unless a contextually clear search control deliberately hides one.</p></div><div className="demo-surface form-demo"><Input label="Business name" hint="Use the registered company name." placeholder="Northstar Trading Ltd" /><Select label="Account currency" placeholder="Choose a currency" defaultValue="" options={[{ label: "Pound sterling", value: "GBP" }, { label: "Euro", value: "EUR" }, { label: "US dollar", value: "USD" }]} /></div></article><article className="component-specimen"><div><h3>Textarea, Checkbox and Radio</h3><p>Native semantics and browser behaviour remain intact beneath Ledger styling.</p></div><div className="demo-surface form-demo"><Textarea label="Payment note" placeholder="Add context for the approver" /><Checkbox label="Include remittance advice" hint="Sent after the payment is released." /><div role="group" aria-labelledby="payment-speed-label"><strong id="payment-speed-label" className="control-group-label">Payment speed</strong><Radio name="payment-speed" label="Standard" defaultChecked /><Radio name="payment-speed" label="Same day" /></div></div></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Data display</p><h2>Semantic Table composition</h2></div><p>Products own the records and financial meaning. Ledger supplies semantic table structure and alignment.</p></div><div className="demo-surface table-scroll"><Table ariaLabel="Example accounts"><TableHead><TableRow><TableHeaderCell>Account</TableHeaderCell><TableHeaderCell>Currency</TableHeaderCell><TableHeaderCell align="right">Available</TableHeaderCell></TableRow></TableHead><TableBody><TableRow><TableCell>Operating account</TableCell><TableCell>GBP</TableCell><TableCell align="right">£248,905.42</TableCell></TableRow><TableRow><TableCell>European operations</TableCell><TableCell>EUR</TableCell><TableCell align="right">€94,620.50</TableCell></TableRow></TableBody></Table></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Public API</p><h2>Current catalogue</h2></div><p>Status and package entry are explicit so proposed concepts cannot be mistaken for installable APIs.</p></div><div className="catalog-filters" aria-label="Catalogue status legend">{statuses.map((status) => <span key={status} data-status={status}>{status}</span>)}</div><div className="component-catalog">{componentCatalog.map((item) => <article key={item.name}><div className="catalog-title"><h3>{item.name}</h3><span data-status={item.status}>{item.status}</span></div><p>{item.purpose}</p><p className="catalog-contract">{item.contract}</p><code>{item.entry}</code></article>)}</div></section>
    <section className="docs-section status-panel"><div><p className="eyebrow">Important distinction</p><h2>Link is a convention, not a React component.</h2></div><p>Applications use semantic anchors and apply <code>.ledger-link</code>. Ledger owns the visual treatment; the application owns routing, external-link detection, permissions and navigation state.</p></section>
  </DocsLayout>;
}
