import { DocsLayout } from "../../_components/DocsLayout";
import { packageEntries } from "@/content/design-system-docs";

export default function InstallationPage() {
  return <DocsLayout eyebrow="Internal workspace availability" title="Installation" intro="Ledger is consumed successfully inside this npm workspace. Registry metadata exists, but a supported external installation and distribution flow has not been verified.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Current usage</p><h2>Import the server-safe root and styles</h2></div><p>The root entry deliberately excludes icons and interactive overlay runtime.</p></div><pre><code>{`import { Button, Input, Table } from\n  "@johnshandux/ledger-design-system";\nimport "@johnshandux/ledger-design-system/styles.css";`}</code></pre></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Interactive data</p><h2>Use the dedicated DataTable entry</h2></div><p>DataTable is separate from the Server Component-safe root because sorting and pagination require client-side interaction.</p></div><pre><code>{`"use client";\n\nimport { DataTable, type DataTableColumn } from\n  "@johnshandux/ledger-design-system/data-table";`}</code></pre></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Package boundaries</p><h2>Public entries</h2></div><p>Use dedicated entries for client interaction families so the root remains safe for Server Component consumers.</p></div><div className="package-entry-list">{packageEntries.map(([entry, purpose]) => <div key={entry}><code>{entry}</code><span>{purpose}</span></div>)}</div><pre><code>{`"use client";\n\nimport { Dialog, DialogContent } from\n  "@johnshandux/ledger-design-system/dialog";`}</code></pre></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Consumer responsibilities</p><h2>What an application still owns</h2></div><p>Ledger supplies UI implementation, not an application framework.</p></div><ul className="prose-list"><li>Load Inter so the authoritative font-family token resolves correctly.</li><li>Import the package stylesheet once at the application boundary.</li><li>Keep dedicated interactive imports in client components.</li><li>Own routing, domain data, permissions, locale overrides and financial meaning.</li><li>Verify package compatibility before relying on an external registry install.</li></ul></section>
    <section className="docs-section status-panel"><div><p className="eyebrow">Distribution status</p><h2>Not yet offered as a verified public install.</h2></div><p>Publishing, external consumer testing, semantic versioning policy and release automation remain milestone work. Existing registry metadata alone is not treated as proof of availability.</p></section>
  </DocsLayout>;
}
