import { DocsLayout } from "../../_components/DocsLayout";
import { tokenGroups } from "@/content/design-system-docs";

const semanticColours = [
  ["Background", "--ledger-color-background", "swatch--background"], ["Text", "--ledger-color-text", "swatch--text"], ["Secondary text", "--ledger-color-text-secondary", "swatch--secondary"], ["Border", "--ledger-color-border", "swatch--border"], ["Action", "--ledger-color-action", "swatch--action"], ["Error action", "--ledger-color-error-action", "swatch--error-action"],
] as const;
const statusColours = [
  ["Neutral", "--ledger-color-status-neutral-background", "status-sample--neutral"], ["Informational", "--ledger-color-status-informational-background", "status-sample--info"], ["Success", "--ledger-color-status-success-background", "status-sample--success"], ["Warning", "--ledger-color-status-warning-background", "status-sample--warning"], ["Error", "--ledger-color-status-error-background", "status-sample--error"],
] as const;

export default function FoundationsPage() {
  const radiusNames = ["none", "small", "medium", "large", "full"];
  const borderNames = ["none", "thin", "thick"];
  const shadowNames = ["none", "small", "medium", "large"];
  return <DocsLayout eyebrow="Implemented" title="Foundations" intro="Ledger’s CSS custom properties are the authoritative visual language for code. Components consume semantic tokens where purpose matters and primitives where a raw scale is genuinely required.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Colour</p><h2>Semantic surfaces and actions</h2></div><p>Ledger is predominantly monochrome. Status colour appears only when it carries meaning and never works as the sole signal.</p></div><div className="swatch-grid">{semanticColours.map(([name, token, className]) => <div className="swatch-card" key={token}><span className={`swatch ${className}`} /><strong>{name}</strong><code>{token}</code></div>)}</div><h3 className="subsection-heading">Status families</h3><div className="status-token-grid">{statusColours.map(([name, token, className]) => <div className={`status-sample ${className}`} key={token}><strong>{name}</strong><code>{token}</code></div>)}</div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Typography</p><h2>Product clarity, selective brand expression</h2></div><p>Inter remains authoritative for product interfaces. Instrument Serif and IBM Plex Mono are reserved for selected LedgerOS brand uses.</p></div><div className="font-role-grid"><article className="font-role-card"><p className="token-label">Product typography · Inter</p><p className="type-heading">Account overview</p><p>Clear interface copy for navigation, controls, forms, tables, labels and standard headings.</p><code>--ledger-font-family-product</code></article><article className="font-role-card"><p className="token-label">LedgerOS display · Instrument Serif</p><p className="brand-display-specimen">Build commercial banking products with confidence.</p><p className="brand-editorial-specimen">Notes from the making of LedgerOS.</p><code>--ledger-font-family-brand-display</code></article><article className="font-role-card"><p className="token-label">LedgerOS supporting · IBM Plex Mono</p><p className="brand-mono-specimen"><span>04 OCT 2026</span><span>ENTRY 0017</span><span>VERSION 1.1.0</span></p><code>--ledger-font-family-brand-mono</code></article></div><div className="type-specimens"><p className="type-display">Display / 40 / 48</p><p className="type-heading">Heading large / 32 / 40</p><p className="type-heading-medium">Heading medium / 24 / 32</p><p className="type-heading-small">Heading small / 20 / 28</p><p>Body / 16 / 24 — Built for clear, data-heavy professional interfaces.</p><p className="small-copy">Body small / 14 / 20</p><p className="token-label">Small / 12 / 16</p></div><div className="foundation-note"><strong>Usage boundary</strong><p>LedgerOS uses Instrument Serif for selected marketing and editorial headings. Inter remains the core typeface for all product interfaces and supporting content. IBM Plex Mono is used selectively for supporting details such as dates, entry numbers, version labels, technical references and code examples. The display serif and monospace families are reserved for LedgerOS brand expression and should not be introduced into product components by default.</p></div></section>
    {tokenGroups.map((group) => <section className="docs-section" key={group.name}><div className="doc-section-heading"><div><p className="eyebrow">Foundation</p><h2>{group.name}</h2></div><p>{group.description}</p></div><div className="token-table" role="table" aria-label={`${group.name} tokens`}><div className="token-table__row token-table__head" role="row"><span role="columnheader">Token</span><span role="columnheader">Value</span><span role="columnheader">Specimen</span></div>{group.tokens.map(([token, value], index) => <div className="token-table__row" role="row" key={token}><code role="cell">{token}</code><span role="cell">{value}</span><span role="cell" className="token-specimen">{group.name === "Spacing" ? <i style={{ width: `var(--ledger-space-${index + 1})` }} /> : group.name === "Radius" ? <i className="radius-specimen" style={{ borderRadius: `var(--ledger-radius-${radiusNames[index]})` }} /> : group.name === "Borders" ? <i className="border-specimen" style={{ borderWidth: `var(--ledger-border-width-${borderNames[index]})` }} /> : <i className="shadow-specimen" style={{ boxShadow: `var(--ledger-shadow-${shadowNames[index]})` }} />}</span></div>)}</div></section>)}
    <section className="docs-section status-panel"><div><p className="eyebrow">Theme status</p><h2>Light, dark and system-aware.</h2></div><p>Semantic colour roles remap between light and dark appearances. With no explicit override, Ledger follows the operating-system preference; accent and branded themes remain future dimensions.</p></section>
  </DocsLayout>;
}
