import { DocsLayout } from "../../_components/DocsLayout";
import { tokenGroups } from "@/content/design-system-docs";

const semanticColours = [
  ["Background", "--ledger-color-background", "swatch--background"], ["Text", "--ledger-color-text", "swatch--text"], ["Secondary text", "--ledger-color-text-secondary", "swatch--secondary"], ["Border", "--ledger-color-border", "swatch--border"], ["Action", "--ledger-color-action", "swatch--action"], ["Error action", "--ledger-color-error-action", "swatch--error-action"],
] as const;
const statusColours = [
  ["Neutral", "--ledger-color-status-neutral-background", "status-sample--neutral"], ["Informational", "--ledger-color-status-informational-background", "status-sample--info"], ["Success", "--ledger-color-status-success-background", "status-sample--success"], ["Warning", "--ledger-color-status-warning-background", "status-sample--warning"], ["Error", "--ledger-color-status-error-background", "status-sample--error"],
] as const;

export default function FoundationsPage() {
  const radiusNames = ["none", "small", "medium", "large", "full"];
  const borderNames = ["none", "thin", "thick"];
  const shadowNames = ["none", "small", "medium", "large"];
  return <DocsLayout eyebrow="Implemented" title="Foundations" intro="Ledger’s CSS custom properties are the authoritative visual language for code. Components consume semantic tokens where purpose matters and primitives where a raw scale is genuinely required.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Colour</p><h2>Semantic surfaces and actions</h2></div><p>Ledger is predominantly monochrome. Status colour appears only when it carries meaning and never works as the sole signal.</p></div><div className="swatch-grid">{semanticColours.map(([name, token, className]) => <div className="swatch-card" key={token}><span className={`swatch ${className}`} /><strong>{name}</strong><code>{token}</code></div>)}</div><h3 className="subsection-heading">Status families</h3><div className="status-token-grid">{statusColours.map(([name, token, className]) => <div className={`status-sample ${className}`} key={token}><strong>{name}</strong><code>{token}</code></div>)}</div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Typography</p><h2>One interface family, explicit roles</h2></div><p>Inter is authoritative today. Applications own framework-specific loading and must make the family behind <code>--ledger-font-family-sans</code> available.</p></div><div className="type-specimens"><p className="type-display">Display / 40 / 48</p><p className="type-heading">Heading large / 32 / 40</p><p className="type-heading-medium">Heading medium / 24 / 32</p><p className="type-heading-small">Heading small / 20 / 28</p><p>Body / 16 / 24 — Built for clear, data-heavy professional interfaces.</p><p className="small-copy">Body small / 14 / 20</p><p className="token-label">Small / 12 / 16</p></div><div className="foundation-note"><strong>Current boundary</strong><p>An editorial marketing family and an authoritative monospace family are not yet defined. Product-specific monospace treatment may remain local until Ledger formalises it.</p></div></section>
    {tokenGroups.map((group) => <section className="docs-section" key={group.name}><div className="doc-section-heading"><div><p className="eyebrow">Foundation</p><h2>{group.name}</h2></div><p>{group.description}</p></div><div className="token-table" role="table" aria-label={`${group.name} tokens`}><div className="token-table__row token-table__head" role="row"><span role="columnheader">Token</span><span role="columnheader">Value</span><span role="columnheader">Specimen</span></div>{group.tokens.map(([token, value], index) => <div className="token-table__row" role="row" key={token}><code role="cell">{token}</code><span role="cell">{value}</span><span role="cell" className="token-specimen">{group.name === "Spacing" ? <i style={{ width: `var(--ledger-space-${index + 1})` }} /> : group.name === "Radius" ? <i className="radius-specimen" style={{ borderRadius: `var(--ledger-radius-${radiusNames[index]})` }} /> : group.name === "Borders" ? <i className="border-specimen" style={{ borderWidth: `var(--ledger-border-width-${borderNames[index]})` }} /> : <i className="shadow-specimen" style={{ boxShadow: `var(--ledger-shadow-${shadowNames[index]})` }} />}</span></div>)}</div></section>)}
    <section className="docs-section status-panel"><div><p className="eyebrow">Theme status</p><h2>Light, dark and system-aware.</h2></div><p>Semantic colour roles remap between light and dark appearances. With no explicit override, Ledger follows the operating-system preference; accent and branded themes remain future dimensions.</p></section>
  </DocsLayout>;
}
