import { DocsLayout } from "../../_components/DocsLayout";

const evidence = [
  { title: "Sterling account overview", source: "Ledger Bank · Accounts", implemented: "The active Northstar fixture presents three GBP accounts using shared Table, Input, Button and formatCurrencyAmount exports.", boundary: "Summary cards, balance aggregation, account data and the mobile account list remain product-owned." },
  { title: "Account transaction history", source: "Ledger Bank · Account detail", implemented: "Semantic Table and currency formatting support the same transaction records in desktop table and mobile list layouts.", boundary: "Transaction direction, status meaning, record data and responsive list presentation remain product-owned. Search and filtering are not implemented." },
  { title: "Financial amount presentation", source: "Design system utility", implemented: "formatCurrencyAmount provides server-safe Intl.NumberFormat output with an en-GB default locale.", boundary: "The utility does not aggregate currencies, infer direction, convert FX, define placeholders or perform financial arithmetic." },
] as const;

export default function PatternsPage() {
  return <DocsLayout eyebrow="Evidence, not packaged APIs" title="Financial patterns" intro="Ledger Bank supplies real product evidence for reusable banking patterns. Those compositions remain application-owned until their contract, accessibility, responsive behaviour and domain boundaries are deliberately specified.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Current evidence</p><h2>What the reference app teaches us</h2></div><p>Implemented examples can guide future standardisation without pretending that every useful screen is already a library pattern.</p></div><div className="pattern-evidence">{evidence.map((item) => <article key={item.title}><div><p className="eyebrow">{item.source}</p><h3>{item.title}</h3></div><dl><div><dt>Reusable today</dt><dd>{item.implemented}</dd></div><div><dt>Still product-owned</dt><dd>{item.boundary}</dd></div></dl></article>)}</div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Candidate areas</p><h2>Potential future contracts</h2></div><p>These are research directions rather than promised exports.</p></div><div className="docs-card-grid"><article className="docs-card"><h3>Account selection</h3><p>Balances, identifiers, permissions and currencies presented without obscuring domain meaning.</p></article><article className="docs-card"><h3>Review and submit</h3><p>Payment details, fees, approval state and consequences made explicit before confirmation.</p></article><article className="docs-card"><h3>Transaction activity</h3><p>Scanning, search and filtering that preserve direction, currency, status and record context.</p></article><article className="docs-card"><h3>Responsive data equivalence</h3><p>Desktop and mobile presentations that preserve the same records, ordering, fields and actions.</p></article></div></section>
    <section className="docs-section status-panel"><div><p className="eyebrow">Promotion rule</p><h2>Evidence before abstraction.</h2></div><p>A product composition becomes a Ledger pattern only when reuse is demonstrated and its domain ownership, component anatomy, states, accessibility and responsive behaviour are documented and reviewed.</p></section>
  </DocsLayout>;
}
