import { DocsLayout } from "../../_components/DocsLayout";
import { agentRules } from "@/content/design-system-docs";

export default function AiGuidancePage() {
  return <DocsLayout eyebrow="Repository guidance implemented · distribution planned" title="AI guidance" intro="Ledger already constrains coding agents through repository instructions, component contracts and package boundaries. A stable distributable machine-readable guidance format is still planned.">
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Working rules</p><h2>How an agent should reason about Ledger</h2></div><p>These principles are drawn from the current repository guidance rather than invented for the website.</p></div><ol className="guidance-list">{agentRules.map(([title, copy], index) => <li key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Financial presentation</p><h2>Do not manufacture domain meaning</h2></div><p>The design system formats values; the product supplies their meaning.</p></div><div className="ownership-grid"><article><h3>Ledger owns</h3><ul><li>Currency-aware display through <code>Intl.NumberFormat</code></li><li>An <code>en-GB</code> default locale</li><li>Tabular numeric presentation styles</li><li>Documented token and component contracts</li></ul></article><article><h3>The product owns</h3><ul><li>The currency source and transaction direction</li><li>Any conversion or valuation policy</li><li>Missing-value semantics and placeholders</li><li>Financial arithmetic, fees, FX and accounting logic</li></ul></article></div></section>
    <section className="docs-section"><div className="doc-section-heading"><div><p className="eyebrow">Grounding model</p><h2>What live generation will require</h2></div><p>The future Playground should retrieve exact system facts before composing an interface.</p></div><div className="grounding-flow" aria-label="Future grounding sequence"><span>Prompt intent</span><i aria-hidden="true">→</i><span>Relevant contracts</span><i aria-hidden="true">→</i><span>Allowed components</span><i aria-hidden="true">→</i><span>Financial constraints</span><i aria-hidden="true">→</i><span>Inspectable result</span></div><div className="foundation-note"><strong>Not implemented yet</strong><p>There is no LLM connection, retrieval layer, stable guidance schema or generated code pipeline in the current Playground.</p></div></section>
  </DocsLayout>;
}
